:copyfrom for MySQL LOAD DATA INFILE
sqlc-dev/sqlc pull request #2220
Opened 2023-04-20 15:47 UTC by Jille

Similar to PostgreSQL :copyfrom support, this adds support for MySQL's LOAD DATA INFILE.

Usage is the same as PostgreSQL: by writing an INSERT INTO query with :copyfrom, and we'll generate a method that internally calls LOAD DATA INFILE.

The only MySQL driver I found that supports LOAD DATA LOCAL INFILE at all is github.com/go-sql-driver/mysql. In able to support other drivers that might add support in the future, the `sql_package` config setting must be set to `go-sql-driver/mysql`.

2023-06-08 00:29 UTC, kyleconroy commented
@Jille I'm assuming this PR is still in draft because of some upstream mysql driver issues?

2023-06-08 07:28 UTC, Jille commented
Yeah, I need go-sql-driver/mysql to expose the *time.Location to encode correctly. But the maintainers don't seem to want to expose it in a way sqlc can use it.

How would you feel about an extra argument to the :loaddata methods that receives the *time.Location with the timezone configured for the connection? It's ugly, but I'm not sure I see another way yet.

2023-06-09 15:05 UTC, kyleconroy commented
> How would you feel about an extra argument to the :loaddata methods that receives the *time.Location with the timezone configured for the connection? It's ugly, but I'm not sure I see another way yet.

I don't think that will play nicely with the `query_parameter_limit` configuration option. We could create a separate struct that has a location as a field? Not sure honestly.

2023-06-25 21:18 UTC, Jille commented
We haven't found a way to expose the timezone from go-sql-driver/mysql yet. Let's move ahead with this and simply block `time.Time` values for now.

2023-07-28 20:34 UTC, kyleconroy requested changes
A few small changes, but other than that I think this is ready to go. I wanted to generate static queries, but it turns out that `LOAD DATA` doesn't work with parameters. Maybe something we can do in the future.

2023-07-28 20:34 UTC, kyleconroy commented on internal/codegen/golang/templates/go-sql-driver-mysql/copyfromCopy.tmpl
> +	result, err := {{if (not $.EmitMethodsWithDBArgument)}}q.{{end}}db.ExecContext(ctx, fmt.Sprintf("LOAD DATA LOCAL INFILE '%s' INTO TABLE {{.TableIdentifierForMySQL}} %s ({{range $index, $name := .Arg
Let's add a comment here explaining that LOAD DATA can't be used with parameters and link to this part of the docs

```
The LOAD DATA INFILE statement reads rows from a text file into a table at a very high speed. The file name must be given as a literal string.
```

2023-07-30 20:01 UTC, kyleconroy commented
Going to get this ready to merge in https://github.com/sqlc-dev/sqlc/pull/2545/. Thanks for the initial implementation :)

2023-07-30 21:53 UTC, kyleconroy commented
Closed via #2545

2023-07-30 21:53 UTC, closed without merging