feat(codegen): add support for build tags (#2012)
sqlc-dev/sqlc pull request #2807
Opened 2023-10-05 13:58 UTC by Hyuga-Tsukui

Attempt at adding the feature for #2012.

I am not a native English speaker, so some variable names might not be appropriate.

I've added a new `build_tags` option, which gets inserted into the template when enabled.

2023-10-05 15:10 UTC, kyleconroy requested changes
Thanks! Only one real change before we can merge this in. Appreciate you adding a test case.

2023-10-05 15:10 UTC, kyleconroy commented on docs/reference/config.md
> +  - build tags to add to the generated code. if you do not want to add it, leave it unset.
```suggestion
  - If set, add a `//go:build <build_tags>` directive at the beginning of each generated Go file.
```

2023-10-05 15:10 UTC, kyleconroy commented on docs/reference/config.md
> +  - build tags to add to the generated code. if you do not want to add it, leave it unset.
```suggestion
  - If set, add a `//go:build <build_tags>` directive at the beginning of each generated Go file.
```

2023-10-05 15:10 UTC, kyleconroy commented on internal/codegen/golang/gen.go
> +	BuildTags string
```suggestion
	BuildTags string
```

2023-10-05 15:10 UTC, kyleconroy commented on internal/codegen/golang/templates/template.tmpl
> +// +build {{.BuildTags}}
The `// +build` syntax has been deprecated since Go 1.17. Let's remove it and only support `//go:build`.

2023-10-05 15:10 UTC, kyleconroy commented on protos/plugin/codegen.proto
> +  string build_tags = 29;
Can you add this to the end of the message instead of in the middle?

2023-10-06 03:28 UTC, Hyuga-Tsukui commented
Thank you for the review. I've made the corrections, so please check again.

2023-10-06 15:56 UTC, kyleconroy approved these changes

2023-10-06 16:07 UTC, merged